---

- hosts: jupyterhub_hosts
  tasks:
    - assert:
        that: (ansible_version.major, ansible_version.minor) >= (2, 1)
        msg: require ansible >= 2.1, found {{ansible_version.full}}

    - command: echo "$PATH"
      register: default_path


- hosts: jupyterhub_hosts
  roles:
    - common
    - python
    - role: r
      when: install_r_kernel
    - role: newrelic
      when: newrelic_license_key is defined and newrelic_license_key != ''
    - nginx
    - supervisor
    - saveusers
    - role: bash
      when: install_bash_kernel
    - jupyterhub
    - role: cull_idle
      when: use_cull_idle_servers
    - role: nbgrader
      when: use_nbgrader
  environment:
      PATH: "/opt/conda/bin:{{ default_path.stdout }}"
