---

- name: apt update
  apt: update_cache=yes cache_valid_time=3600
  become: yes

- name: install aptitude
  apt: pkg=aptitude
  become: yes

# upgrade requires aptitude
- name: apt upgrade
  apt: upgrade=safe
  become: yes

- name: build-essential
  apt: pkg=build-essential state=present
  become: true

- name: other developer tools
  apt: pkg={{item}} state=present
  become: true
  with_items:
    - gfortran
    - git

- name: install user applications
  apt: pkg={{item}} state=present
  become: true
  with_items:
    - vim
    - emacs
    - tree
    - htop

- name: install open-iscsi for cloud block volumes
  apt: pkg=open-iscsi state=present
  become: true
